"""describe changes

Revision ID: 54a2c95aca54
Revises: ff6819b01e2f
Create Date: 2026-02-08 21:52:25.126233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a2c95aca54'
down_revision: Union[str, Sequence[str], None] = 'ff6819b01e2f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('transactions', sa.Column('needs_review', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'needs_review')
    op.drop_column('transactions', 'ai_confidence')
    # ### end Alembic commands ###
