[pytest]
env =
    TEST_DATABASE_NAME=finance_test_db
    DATABASE_HOSTNAME=localhost
    DATABASE_PORT=5432
    DATABASE_USERNAME=postgres
    DATABASE_PASSWORD=arpitraj@020415
    SECRET_KEY=test_secret_key_1234
    ALGORITHM=HS256
    ACCESS_TOKEN_EXPIRE_MINUTES=30
    GEMINI_API_KEY=test-api-key
    GEMINI_MODEL_NAME=gemini-3-flash-preview
    DATABASE_NAME=finance_test_db
    DATABASE_URL=postgresql+psycopg2://postgres:arpitraj@020415@localhost:5432/finance_test_db
